[OnlineSubsystemMcp.Xmpp]
bUseSSL=false
ServerAddr="ws://35.221.95.153:80"
ServerPort=80

[OnlineSubsystemMcp.Xmpp Prod]
bUseSSL=false
ServerAddr="ws://35.221.95.153:80"
ServerPort=80

[OnlineSubsystemMcp.OnlineWaitingRoomMcp]
bEnabled=35.221.95.153
ServiceName="waitingroom"
GracePeriod=300
RetryConfigUrl="https://s3-us-west-1.amazonaws.com/launcher-resources/waitingroom"

[OnlineSubsystemMcp]
bUsePartySystemV2=35.221.95.153

[OnlineSubsystemMcp.OnlinePartySystemMcpAdapter]
bUsePartySystemV2=35.221.95.153

[CrashContextProperties]
CrashReportClientRichText=NSLOCTEXT("FortGlobals", "FortniteCrashReportClientText", "Fortnite has crashed.")

[/Script/Qos.QosRegionManager]
NumTestsPerRegion=2
PingTimeout=3.0
!RegionDefinitions=ClearArray
+RegionDefinitions=(DisplayName="ASIA[Tokyo]", RegionId="ASIA", bEnabled=true, bVisible=true, bAutoAssignable=true)
!DatacenterDefinitions=ClearArray
#+DatacenterDefinitions=(Id="VA", RegionId="NAE", bEnabled=true, Servers[0]=(Address="ping-nae.ds.on.epicgames.com", Port=22222))
+DatacenterDefinitions=(Id="ASIA", RegionId="ASIA", bEnabled=true, Servers[0]=(Address="ping-asia.ds.on.epicgames.com", Port=22222))

[XMPP]
bEnableWebsockets=true

[LwsWebSocket]
bDisableCertValidation=true


[/Script/Engine.Engine] ## this aslo makes faster but not that much tbh
NetClientTicksPerSecond=120

[/Script/OnlineSubsystemUtils.IpNetDriver] # makes baceknd SO MUCH FASTER
NetServerMaxTickRate=120
LanServerMaxTickRate=120
MaxNetTickRate=120
MaxClientRate=104857600
MaxInternetClientRate=104857600
MinClientRate=10485760
MinInternetClientRate=10485760
InitialConnectTimeout=300.0
ConnectionTimeout=300.0
KeepAliveTime=0.2
RelevantTimeout=5.0
SpawnPrioritySeconds=1.0
ServerTravelPause=4.0
NetConnectionClassName="/Script/OnlineSubsystemUtils.IpConnection"

[/Script/Engine.NetworkSettings]
n.VerifyPeer=false

[ConsoleVariables] # Fix for kick
net.AllowEncryption=0
n.VerifyPeer=0
FortMatchmakingV2.ContentBeaconFailureCancelsMatchmaking=0
Fort.ShutdownWhenContentBeaconFails=0
FortMatchmakingV2.EnableContentBeacon=0




# Double Pump
[ConsoleVariables]
n.VerifyPeer=0
FortMatchmakingV2.ContentBeaconFailureCancelsMatchmaking=0
Fort.ShutdownWhenContentBeaconFails=0
FortMatchmakingV2.EnableContentBeacon=0
;Weapon.TryToFireRestrictedByTypeCooldowns=0

;Glider redeploy? Not working???
;Fort.GliderRedeployRequiresJump=1
;Fort.GliderRedeployUseWindowOfTime=0
;Fort.GliderRedeployWindowLength=5.0
;Fort.GliderRedeployPreventSkydiving=1

;Not sure yet, appears to change graphics somehow
;[/Script/FortniteGame.FortWorldSettings]
;DefaultWorldTimeOfDayManager=/Game/TimeOfDay/TODM/MASTER_TODM.MASTER_TODM_C

;Disable first shot accuracy
;[/Script/FortniteGame.FortGlobals]
;bFirstShotAccuracyDisabled=false